### ISSUE TITLE
Document available icons. 

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/entypo#1]
It would be cool to list off all the names of icons with a preview or something for copy pasta magic.

**Comment by ungoldman** [comment]
👍 yep

could we replicate what we did with `@zhealth/icons` and publish to gh-pages?

**Comment by bcomnes** [comment]
Oh yeah good idea

**Comment by ungoldman** [comment]
Fixed in #4

**Comment by bcomnes** [comment]
Nice! Looks great.

**Comment by ungoldman** [comment]
Thanks! Try `npm run example` 😁

**Comment by bcomnes** [comment]
Whoops, missing budo.

**Comment by ungoldman** [comment]
Aw snap, must have removed it when doing some git fu. I'll add it in a sec along with brfs as dev dep.

**Comment by bcomnes** [comment]
and brfs.  Should I add?

**Comment by ungoldman** [comment]
Done in 72143374524b2a0e3b2c11233e2fe06edc8f2037

**Comment by bcomnes** [comment]
Looks awesome.  We should put it on ghpages.

![screen shot 2016-12-17 at 6 28 38 pm](https://cloud.githubusercontent.com/assets/166301/21291049/b6ef490a-c486-11e6-8987-e57427723b24.png)

**Comment by ungoldman** [comment]
Yeah just need to figure out a smart way to do it, budo isn't static-build friendly.

**Comment by ungoldman** [comment]
If we're going to publish that to gh-pages we should add a small usage block to the top, like:

```html
<svg><use xlink:href="#entypo-star" /></svg>
```
