### ISSUE TITLE
deprecate and remove rawPath method?

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/entypo#6]
I think if a user wants the entire Entypo+ collection they can just download it.

I think we should move towards excluding the `Entypo+` directory from the package when publishing so users aren't needlessly getting an extra copy of the font collection buried in their `node_modules` directory.

This would mean deprecating `rawPath` in a minor release, then removing it and adding `Entypo+` to `.npmignore` in a major release.

**Comment by bcomnes** [comment]
The reason I threw it in there was for people who want to use entypo, but maybe not use the entypo svg sprite sheet approach, and instead use their own build system.  

Maybe we can ~~depreciate~~ remove those, npmignore the raw assets, and if someone comes along in the future wanting this feature we can revert the change.

**Comment by ungoldman** [comment]
hmm i guess i can see that being a thing. just wary of including a big raw asset folder in a distro.

**Comment by ungoldman** [comment]
also `Entypo+/Entypo+/` 😢 
maybe we could call it `src/`?

**Comment by ungoldman** [comment]
or `icons/`

**Comment by ungoldman** [comment]
I think the `Icon` files in there are OS artifacts or something

**Comment by bcomnes** [comment]
Would make the folder paths nicer to work with.

**Comment by ungoldman** [comment]
Removed `Icon?` files as they're just there to act as directory icons, and they seem to have been zeroed out by git or something else anyway.

**Comment by bcomnes** [comment]
Closed by v2.0.0.
